repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.8
    hooks:
      - id: ruff-check
      - id: ruff-format
        args: ["--check", "--diff"]

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: uv run mypy . --check-untyped-defs
        language: system
        types: [python]
        pass_filenames: false
